"""added is_admin feature

Revision ID: 17e16de2ba3a
Revises: d7efc13eafde
Create Date: 2021-11-18 14:18:07.740093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e16de2ba3a'
down_revision = 'd7efc13eafde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasklogin-users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasklogin-users', 'is_admin')
    # ### end Alembic commands ###
