"""added a description to pharmacy model

Revision ID: d7efc13eafde
Revises: 0072d9e66e16
Create Date: 2021-11-18 11:57:49.485447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7efc13eafde'
down_revision = '0072d9e66e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacies', 'description')
    # ### end Alembic commands ###
